site_name: Prologue
site_description:  Elegant and high performance Web Framework.

theme:
    name: 'material'

repo_name: planety/prologue
repo_url: https://github.com/planety/prologue
edit_uri: ""

nav:
    - Introduction: "index.md"
    - QuickStart: "quickstart.md"
    - Application: "application.md"
    - Configure: "configure.md"
    - Event: "event.md"
    - Error Handler: "errorhandler.md"
    - Headers: "headers.md"
    - Requests: "request.md"
    - Response: "response.md"
    - Context: "context.md"
    - Route: "route.md"
    - Middleware: "middleware.md"
    - Static Files: "staticfiles.md"
    - Upload Files: "uploadfile.md"
    - Session: "session.md"
    - Server Settings: "server.md"
    - WebSocket: "websocket.md"
    - Command Line Tool: "cli.md"
    - Views: "views.md"
    - OpenApi Docs: "openapi.md"
    - FAQ: "faq.md"


markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc
